# Generated by Django 3.0.7 on 2020-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('username', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=75)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
