# Generated by Django 3.0.7 on 2020-07-28 21:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=user.models.Users)),
                ('friend_id', models.IntegerField(verbose_name=user.models.Users)),
            ],
            options={
                'db_table': 'friends',
                'unique_together': {('user_id', 'friend_id')},
            },
        ),
    ]
