# Generated by Django 3.0.7 on 2020-07-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
